### ISSUE TITLE
Domain chookie detection

### ISSUE THREAD

**Issue by Tanerx** [Privacy-Managers/Privacy-Manager#92] opened 2020-11-20 06:55 UTC
Hi dev.
I'am moving firefox based browser to opera. I was using [smilar extension](https://github.com/Lusito/forget-me-not/) for cookies. (Delete all except whitelist) altinstar.com not visible in Privacy-Manager.  I can't whitelist this domain. Can i get help ? Or this is bug need to fix ?

Thanks.

**Comment by Manvel** [comment] 2020-12-06 12:33
Hi @Tanerx 

Thanks for reaching out and apologies for late reply(temporarily I have  limited availability for keyboard and internet).

I'm not able to reproduce your issue and seems like `altinstar.com` is visible in the cookies tab, please ensure current preconditions:
- `Additional permissions` checkbox in the `Cookies` tab is turned on
- `Search domain` doesn't filtering out `altinstar.com`

In order to whitelist `altinstar.com` please use whitelisting button(next to the delete - `X` button) for `altinstar.com` domain and after you can use `Delete All` button for deleting cookies, besides the ones that have been whitelisted.

<img width="509" alt="Screen Shot 2020-12-06 at 4 27 25 PM" src="https://user-images.githubusercontent.com/716969/101280009-eee2ae80-37df-11eb-8009-c45332d8d5a1.png">

Please let me know if you still might have issue and I'll try answering as soon I get an access.

Best,
Manvel

**Comment by Tanerx** [comment] 2020-12-06 13:01
Hi Manvel

This is not working for me. Maybe because i'm using Opera ?

https://i.imgur.com/YwY6CRb.png

**Comment by Manvel** [comment] 2020-12-06 13:37
That's strange, I can confirm that it works on my side:
<img width="1310" alt="Screen Shot 2020-12-06 at 5 34 38 PM" src="https://user-images.githubusercontent.com/716969/101281601-53563b80-37e9-11eb-957d-0fe7c1b893cd.png">


Wonder if you actually have those cookies set in the browser?
<img width="1256" alt="Screen Shot 2020-12-06 at 5 37 05 PM" src="https://user-images.githubusercontent.com/716969/101281656-aa5c1080-37e9-11eb-8f43-d3292bbf4983.png">

**Comment by Tanerx** [comment] 2020-12-06 13:58
Very strange. I dont have this chookie. To keep my login not deleted every time i set keep Local Storage just for altinstar. But some settings still resetting.

https://i.imgur.com/r3giyP6.png 

I dont want to waste your time. Just one web page. I can live with it 👍

**Comment by Manvel** [comment] 2020-12-06 14:09
Probably something blocking those cookies to be set in the browser.

Will close this issue for now, but let me know if you might need further assistance and/or question.

Best,
Manvel

**Closed by Manvel** 2020-12-06 14:09 UTC

**Comment by Tanerx** [comment] 2020-12-06 14:42
> Probably something blocking those cookies to be set in the browser.

Thanks for hint. I test all my extension. I found 2 extension blocking creating chookies same time. Privacy Badger and Ublock Origin.

Thank you.
